### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Jackielc** [Tangdixi/DCExplosion#1]
Under the tableView option,when i destroy all cell and refresh it ,then select the cell,Xcode console output without animation :
    error : `Example (Explodable)[1122:232615] Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.` 
You can look at it !

**Comment by Tangdixi** [comment]
Hi @SmithCaoCao, Can U show me your code?

**Comment by SmithCaoCao** [comment]
Run your project directly, not my code

**Comment by SmithCaoCao** [comment]
iPhone 6s Plus 9.3

**Comment by Jackielc** [comment]
Run your project directly, not my code, iPhone 6s plus ,iOS 9.3

**Comment by Tangdixi** [comment]
Everything works fine ... I don't see anything in Xcode output. 😳

**Comment by Tangdixi** [comment]
I just update the example related code, try again PLZ

**Comment by Jackielc** [comment]
@Tangdixi okay

**Comment by Tangdixi** [comment]
@SmithCaoCao cheer 🍻
