### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by Esqarrouth** [Tangdixi/DCExplosion#2]
You might want to create a new branch that includes the Swift 2 version, and convert this to Swift 3.

**Comment by Tangdixi** [comment]
Trust me, I want to do that. But I M busy with my work now ...
I'll start the Swift 3 version soon ~

**Comment by Esqarrouth** [comment]
No hurries, I'm still using Swift 2.2 anyways.

**Comment by Tangdixi** [comment]
Migrate to Swift 3 done.
